name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: coursier cache
      uses: actions/cache@v2.1.3
      if: runner.OS == 'Linux'
      with:
        path: ~/.cache/coursier
        key: ${{ runner.OS }}-coursier-cache-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
        restore-keys: |
          ${{ runner.OS }}-coursier-cache-${{ hashFiles('**/*.sbt') }}-
          ${{ runner.OS }}-coursier-cache-

    - uses: olafurpg/setup-scala@v12
      with:
        java-version: adopt@1.8.0-232

    - name: Compile
      run: csbt test

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: coursier cache (Linux)
        uses: actions/cache@v2.1.3
        if: runner.OS == 'Linux'
        with:
          path: ~/.cache/coursier
          key: ${{ runner.OS }}-coursier-cache-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
          restore-keys: |
            ${{ runner.OS }}-coursier-cache-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.OS }}-coursier-cache-

      - uses: olafurpg/setup-scala@v12

      - uses: olafurpg/setup-gpg@v3

      - name: Release
        run: csbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
